# **ManipulaciÃ³n de columnas**

In [4]:
import pandas as pd

df = pd.read_csv("Online_Retail.csv", encoding="windows-1252")
df["TotalPrice"] = df["Quantity"] * df["UnitPrice"]

print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
0  12/1/10 8:26       2.55     17850.0  United Kingdom       15.30
1  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34
2  12/1/10 8:26       2.75     17850.0  United Kingdom       22.00
3  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34
4  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34

In [5]:
df["HighValue"] = df["TotalPrice"] > 100
print(df["HighValue"].head(3))

0    False
1    False
2    False
Name: HighValue, dtype: bool

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
 8   TotalPrice   541909 non-null  float64
 9   HighValue    541909 non-null  bool
dtypes: bool(1), float64(3), int64(1), object(5)
memory usage: 37.7+ MB
None

In [8]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
print(df.info())

<ipython-input-8-bc56417708a6>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
 8   TotalPrice   541909 non-null  float64
 9   HighValue    541909 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 37.7+ MB
None

In [10]:
df['DiscountedPrice'] = df["UnitPrice"].apply(lambda x: x* 0.9)
print(df.head(3))

  InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                 WHITE METAL LANTERN         6
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00

   HighValue  DiscountedPrice
0      False            2.295
1      False            3.051
2      False            2.475

In [14]:
def categorize_price(price):
  if price > 50:
    return "High"
  elif price < 20:
    return "Medium"
  else:
    return "Low"
df["PriceCategory"] = df["UnitPrice"].apply(categorize_price)
print(df.head(10))

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
5    536365     22752         SET 7 BABUSHKA NESTING BOXES         2
6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6
7    536366     22633               HAND WARMER UNION JACK         6
8    536366     22632            HAND WARMER RED POLKA DOT         6
9    536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
5 2010-12-01 08:26:00       7.65     17850.0  United Kingdom       15.30
6 2010-12-01 08:26:00       4.25     17850.0  United Kingdom       25.50
7 2010-12-01 08:28:00       1.85     17850.0  United Kingdom       11.10
8 2010-12-01 08:28:00       1.85     17850.0  United Kingdom       11.10
9 2010-12-01 08:34:00       1.69     13047.0  United Kingdom       54.08

   HighValue  DiscountedPrice PriceCategory
0      False            2.295        Medium
1      False            3.051        Medium
2      False            2.475        Medium
3      False            3.051        Medium
4      False            3.051        Medium
5      False            6.885        Medium
6      False            3.825        Medium
7      False            1.665        Medium
8      False            1.665        Medium
9      False            1.521        Medium